Migrate from setup.py to pyproject.toml (#315)
* Add npm scripts for building

* Convert project to use hatch jupyter builder

* Replace setup.py jsversion with tbump

* Fix javascript version not consistent with project version

* Update manual release instructions

* Update cache hash key

* Fix issues with build scripts

* Fix hatch-jupyter-build requires Python 3.8+

* Move copy build step to js script

* Apply pyproject-fmt

diff --git a/git-hooks/post-checkout b/git-hooks/post-checkout
--- a/git-hooks/post-checkout
+++ b/git-hooks/post-checkout
@@ -11,12 +11,12 @@ if [[
   ! -z "$(git diff $PREVIOUS_HEAD nbclassic/static/*/js/**.js)"
 ]]; then
   echo "rebuilding javascript"
-  python setup.py js || echo "fail to rebuild javascript"
+  npm run build:js || echo "fail to rebuild javascript"
 fi
 
 if [[
   ! -z "$(git diff $PREVIOUS_HEAD nbclassic/static/*/less/**.less)"
 ]]; then
   echo "rebuilding css sourcemaps"
-  python setup.py css || echo "fail to recompile css"
+  npm run build:css || echo "fail to recompile css"
 fi
